sudo: required
services:
  - docker

before_install:
  - docker build -t cr9ver/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true cr9ver/react-test npm test

after_sucess:
  - docker build -t cr9ver/multi-client ./client
  - docker build -t cr9ver/multi-nginx ./nginx
  - docker build -t cr9ver/multi-server ./server
  - docker build -t cr9ver/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push cr9ver/multi-client
  - docker push cr9ver/multi-nginx
  - docker push cr9ver/multi-server
  - docker push cr9ver/multi-worker

deploy:
  provider: elasticbeanstalk
  region: "eu-west-2"
  app: "multi-docker"
  env: "Docker-multi-env"
  bucket_name: "elasticbeanstalk-eu-west-2-685794242424"
  bucket_path: "multi-docker"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: "$AWS_SECRET_KEY"